"""Add candidate resume parsing data

Revision ID: 0a9f3df03f4b
Revises: 5a4b6e52bd11
Create Date: 2026-09-05 19:14:51.253227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9f3df03f4b'
down_revision = '5a4b6e52bd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('portfolio_url', sa.String(length=512), nullable=True))

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('processing_error', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('ix_resumes_is_current', ['is_current'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index('ix_resumes_is_current')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('processing_error')
        batch_op.drop_column('is_current')
        batch_op.drop_column('version')
        batch_op.drop_column('parsed_data')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('portfolio_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('linkedin_url')

    # ### end Alembic commands ###
