"""Add job description metadata

Revision ID: 5a4b6e52bd11
Revises: a30239d85e44
Create Date: 2026-09-05 19:11:38.991118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4b6e52bd11'
down_revision = 'a30239d85e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jd_original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('jd_stored_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('jd_file_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('jd_file_path')
        batch_op.drop_column('jd_stored_filename')
        batch_op.drop_column('jd_original_filename')

    # ### end Alembic commands ###
