"""Add semantic matching score details

Revision ID: aae4caefa94c
Revises: 0a9f3df03f4b
Create Date: 2026-09-05 19:20:51.131743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae4caefa94c'
down_revision = '0a9f3df03f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semantic_score', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('matched_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('missing_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('partial_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_scores', schema=None) as batch_op:
        batch_op.drop_column('explanation')
        batch_op.drop_column('partial_skills')
        batch_op.drop_column('missing_skills')
        batch_op.drop_column('matched_skills')
        batch_op.drop_column('semantic_score')

    # ### end Alembic commands ###
