"""Add application shortlist state

Revision ID: ce82bccffe8c
Revises: aae4caefa94c
Create Date: 2026-09-05 19:59:23.835588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce82bccffe8c'
down_revision = 'aae4caefa94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shortlisted', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('is_shortlisted')

    # ### end Alembic commands ###
